name: Build .NET and Publish Invoice Microservice to Docker Hub
 
on:
  push:
    branches: ["main"]  # Change if your main branch has a different name
 
env:
  DOTNET_VERSION: '9.0.x'  # .NET 9
  DOCKER_IMAGE_NAME: 'leo2706/invoice-microservice'  # Change this
  HELM_REPO: 'LuisOlayaNRA/microservices-infra'  # Your helm charts repo
  CHART_PATH: 'invoice-chart'  # Path to your invoice chart in the helm repo
 
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
 
      # Setup .NET
      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
 
      # Restore and build all projects (optional)
      - name: Build Solution
        run: dotnet build --configuration Release
 
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
      # Build and push only the Invoice microservice
      - name: Build and Push Invoice Microservice
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Microservicios/Invoice/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      # --- STAGE 3: Update Helm Chart ---
      - name: Checkout Helm Charts repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.HELM_REPO }}
          token: ${{ secrets.HELM_REPO_TOKEN }}
          path: helm-charts
 
      - name: Update Helm Chart
        run: |
         cd helm-charts/${{ env.CHART_PATH }}
         # More robust replacement commands
         sed -i "s|^\(\s*repository\s*:\s*\).*|\1${{ env.DOCKER_IMAGE_NAME }}|" values.yaml
         sed -i "s|^\(\s*tag\s*:\s*\).*|\1latest|" values.yaml
         # Debug: Show changes
         git diff
         # Only commit if changes were made
         if git diff --quiet; then
           echo "No changes detected"
         else
           git config --global user.name "GitHub Actions"
           git config --global user.email "actions@github.com"
           git add values.yaml
           git commit -m "Auto-update invoice image to latest [skip ci]"
           git push
         fi